name: BoostSecurity Snyk
env:
  SNYK_TOKEN: 130a3a8d-cf45-429d-9070-7fa14f3cc8ef
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - synchronize
jobs:
  scanner:
    name: Snyk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Gemfile
        run: |
          echo "source 'https://rubygems.org'" > Gemfile
          echo "gem 'paperclip', git: '$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git'" >> Gemfile
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Snyk
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          api_token: ${{ secrets.BOOST_API_TOKEN }}
          registry_module: boostsecurityio/snyk-test
          additional_args: --log-level DEBUG --log-verbose
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN  }}
